// Generated by CoffeeScript 1.6.2
(function() {
  var Main;

  Main = (function() {
    Main.prototype.defaults = {
      transition: 1500,
      delay: 4000,
      rainbowTime: 30000,
      particleDelay: 0
    };

    function Main(o) {
      this.o = o != null ? o : {};
      this.vars();
      this.animateRainbow();
      this.animate();
    }

    Main.prototype.vars = function() {
      this.settings = this.extend(this.defaults, this.o);
      this.currentProgress = 2000;
      this.rainbow = document.getElementById('rainbow');
      this.process = document.getElementById('js-process');
      this.easing = TWEEN.Easing.Quadratic.In;
      return this.animate = this.bind(this.animate, this);
    };

    Main.prototype.extend = function(obj, obj2) {
      var key, value;

      for (key in obj2) {
        value = obj2[key];
        if (obj2[key] != null) {
          obj[key] = value;
        }
      }
      return obj;
    };

    Main.prototype.setProgress = function(n) {
      var it, tween;

      n = this.normalizeNum(n);
      it = this;
      return tween = new TWEEN.Tween({
        p: this.currentProgress
      }).to({
        p: n
      }, this.settings.transition).onUpdate(function() {
        it.process.setAttribute('stroke-dashoffset', this.p);
        return it.currentProgress = this.p;
      }).start();
    };

    Main.prototype.animateRainbow = function() {
      var it, tween;

      it = this;
      return tween = new TWEEN.Tween({
        deg: 0
      }).to({
        deg: 360
      }, this.settings.rainbowTime).onUpdate(function() {
        return it.rainbow.setAttribute('transform', 'rotate(' + this.deg + ', 500, 500)');
      }).start().repeat(9999999999999999);
    };

    Main.prototype.normalizeNum = function(n) {
      n = n % 101;
      n = n / 100;
      n *= 2000;
      return n = 2000 - n;
    };

    Main.prototype.animate = function() {
      requestAnimationFrame(this.animate);
      return TWEEN.update();
    };

    Main.prototype.bind = function(func, context) {
      var bindArgs, wrapper;

      wrapper = function() {
        var args, unshiftArgs;

        args = Array.prototype.slice.call(arguments);
        unshiftArgs = bindArgs.concat(args);
        return func.apply(context, unshiftArgs);
      };
      bindArgs = Array.prototype.slice.call(arguments, 2);
      return wrapper;
    };

    return Main;

  })();

  window.Loading = Main;

}).call(this);

/*
//@ sourceMappingURL=main.map
*/
